#!/bin/sh

set -ex

cd "$(dirname "$0")/.."

VERSION=$(grep -e "^version" cli/Cargo.toml | cut -d ' ' -f 3 | tr -d '"')
echo $VERSION

grep -Fq "https://reinfer.io/public/cli/bin/x86_64-unknown-linux-musl/$VERSION/re" README.md || \
    (echo "README.md has out-of-date Linux binary link" && exit 1)

grep -Fq "https://reinfer.io/public/cli/bin/x86_64-apple-darwin/$VERSION/re" README.md || \
    (echo "README.md has out-of-date macOS binary link" && exit 1)

grep -Fq "https://reinfer.io/public/cli/debian/reinfer-cli_${VERSION}_amd64.deb" README.md || \
    (echo "README.md has out-of-date deb link" && exit 1)
