#!/bin/bash

set -ex

cd "$(dirname "$0")/.."
ROOT="$PWD"

cd "$ROOT/api"
cargo publish

# Wait for crates.io metadata to update with the new crate we just published
# Otherwise we get a 'no such dependency' error
sleep 10

cd "$ROOT/cli"
cargo publish
