#!/bin/bash

set -ex

case $BUILD_PLATFORM in
  "ubuntu-20.04")
    rustup target add x86_64-unknown-linux-musl
    sudo apt-get install          \
      musl-tools                  \
      python3-toml
    cargo install cargo-deb
    ;;
  "macos-15")
    rustup target add x86_64-apple-darwin
    rustup target add x86_64-pc-windows-gnu
    pip install toml
    brew install mingw-w64
    ;;
  *)
    >&2 echo "fatal: unknown BUILD_PLATFORM '$BUILD_PLATFORM'"
    exit 1
    ;;
esac
