name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        if: ${{ matrix.os != 'macos-12' }}
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: ./scripts/build
      - name: Run tests
        run: ./scripts/check
        env:
          REINFER_CLI_TEST_PROJECT: ${{ secrets.REINFER_CLI_TEST_PROJECT }}
          REINFER_CLI_TEST_TOKEN: ${{ secrets.REINFER_CLI_TEST_TOKEN }}
          REINFER_CLI_TEST_ENDPOINT: ${{ secrets.REINFER_CLI_TEST_ENDPOINT }}
      - name: Install publish dependencies
        run: ./scripts/publish-install
        env:
          BUILD_PLATFORM: ${{ matrix.os }}
      - name: GCP Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - uses: google-github-actions/setup-gcloud@v1
        name: Set up Cloud SDK
      - name: Publish Binaries
        run: ./cli/publish-binaries
        env:
          BUILD_PLATFORM: ${{ matrix.os }}
      - name: Publish Crates
        if: ${{ matrix.os == 'ubuntu-20.04' }}
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          ./scripts/publish
