name: Publish

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: ./scripts/build
      - name: Run tests
        run: ./scripts/check
        env:
          REINFER_CLI_TEST_ORG: ${{ secrets.REINFER_CLI_TEST_ORG }}
          REINFER_CLI_TEST_TOKEN: ${{ secrets.REINFER_CLI_TEST_TOKEN }}
      - name: Install publish dependencies
        run: ./scripts/publish-install
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "299.0.0"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Publish Binaries
        run: ./cli/publish-binaries
      - name: Publish Crates
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          ./scripts/publish
